SELECT TRAVEL_STATUS_DESTINATION, COUNT(TRAVELER_ID)
    FROM tn_traveller_master
        GROUP BY TRAVEL_STATUS_DESTINATION;

SELECT TRAVEL_STATUS_DESTINATION, COUNT(TRAVELER_ID)
    FROM tn_traveller_master
        WHERE TRAVEL_STATUS_ACCOMPANY = '나홀로 여행'
        GROUP BY TRAVEL_STATUS_DESTINATION;

SELECT TRAVEL_STATUS_DESTINATION, COUNT(TRAVELER_ID)
    FROM tn_traveller_master
        WHERE TRAVEL_STATUS_ACCOMPANY <> '나홀로 여행'
        GROUP BY TRAVEL_STATUS_DESTINATION;